server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234!

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 68a71cd25348a14a6a5da12dd5b301f8
            clientSecret :  kopEZmx1CcjqKBdgGUEfJxdW0ldogwEV
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          google:
            clientId: 65506729661-7l1qo62h8fg86bhg0ibekn7mngn2vuej.apps.googleusercontent.com
            clientSecret: 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
            redirectUri:  "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - email
            - profile
          facebook:
            clientId: 564548221247032
            clientSecret: 6a9f826399e60fbba76968187b95adc3
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - email
            - public_profile
          naver:
            clientId: b5FPit4F7iPERZUotS5b
            clientSecret: DEsMji4kmi
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - name
            - email
#            client-name: Naver
#            authorization-grant-type: authorization_code
            
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response  # 회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#          facebook:
#              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
#              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
#tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect             
          
